/**
 * Icon Library - Auto-generated from Figma
 *
 * This file exports all icon components and related types.
 * Do not edit this file manually - it is generated by the build process.
 */

import { IconBaoGaoZhuShou } from './icons/IconBaoGaoZhuShou';
import { IconChengYuanGuanLi } from './icons/IconChengYuanGuanLi';
import { IconSouSuoZhuShou } from './icons/IconSouSuoZhuShou';

export { IconBaoGaoZhuShou, type IconBaoGaoZhuShouProps } from './icons/IconBaoGaoZhuShou';
export { IconChengYuanGuanLi, type IconChengYuanGuanLiProps } from './icons/IconChengYuanGuanLi';
export { IconSouSuoZhuShou, type IconSouSuoZhuShouProps } from './icons/IconSouSuoZhuShou';

/**
 * Object containing all icon components
 */
export const allIcons = {
  IconBaoGaoZhuShou,
  IconChengYuanGuanLi,
  IconSouSuoZhuShou
} as const;

/**
 * Union type of all icon component names
 */
export type IconName = keyof typeof allIcons;
