/**
 * Icon Library - Auto-generated from Figma
 *
 * This file exports all icon components and related types.
 * Do not edit this file manually - it is generated by the build process.
 */

import { IconArrowRight } from './icons/IconArrowRight';
import { IconCheck } from './icons/IconCheck';
import { IconCloseCircle } from './icons/IconCloseCircle';
import { IconQiYeBan } from './icons/IconQiYeBan';
import { IconXiaZaiZhuShou } from './icons/IconXiaZaiZhuShou';
import { IconXiTongPeiZhi } from './icons/IconXiTongPeiZhi';
import { IconYunYingGuanLi } from './icons/IconYunYingGuanLi';

export { IconArrowRight, type IconArrowRightProps } from './icons/IconArrowRight';
export { IconCheck, type IconCheckProps } from './icons/IconCheck';
export { IconCloseCircle, type IconCloseCircleProps } from './icons/IconCloseCircle';
export { IconQiYeBan, type IconQiYeBanProps } from './icons/IconQiYeBan';
export { IconXiaZaiZhuShou, type IconXiaZaiZhuShouProps } from './icons/IconXiaZaiZhuShou';
export { IconXiTongPeiZhi, type IconXiTongPeiZhiProps } from './icons/IconXiTongPeiZhi';
export { IconYunYingGuanLi, type IconYunYingGuanLiProps } from './icons/IconYunYingGuanLi';

/**
 * Object containing all icon components
 */
export const allIcons = {
  IconArrowRight,
  IconCheck,
  IconCloseCircle,
  IconQiYeBan,
  IconXiaZaiZhuShou,
  IconXiTongPeiZhi,
  IconYunYingGuanLi
} as const;

/**
 * Union type of all icon component names
 */
export type IconName = keyof typeof allIcons;
